import { StandardButton, Button, VerticalBox, LineEdit, Switch, GroupBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property <string> footer: "";
    in-out property <string> archive_path: "";
    in-out property <string> game_path: "";
    in-out property <bool> overwrite: true;
    in-out property <bool> direct: false;
    in-out property <bool> show_about_window: false;

    callback request_archive_path();
    callback request_game_path();
    callback mod();

    title: "Game Modding Tool";
    min-height: 150px;
    min-width: 600px;

    MenuBar {
        Menu {
            title: @tr("Help");
            MenuItem {
                title: @tr("About");

                activated => {
                    about_popup.show();
                }
            }
        }
    }

    VerticalLayout {
        spacing: 10px;
        padding: 50px;

        VerticalLayout {
            Text {
                text: "Path to directory containing compressed files ( RAR - ZIP - 7z)";
                horizontal-alignment: center;
            }

            HorizontalLayout {
                spacing: 10px;
                LineEdit {
                    text: root.archive_path;
                    edited(text) => {
                        root.archive_path = text;
                    }
                }

                Button {
                    width: 200px;
                    text: "Open directory";
                    clicked => {
                        root.request_archive_path();
                    }
                }
            }
        }

        VerticalLayout {
            Text {
                text: "Path to game directory";
                horizontal-alignment: center;
                vertical-alignment: center;
            }

            HorizontalLayout {
                spacing: 10px;
                LineEdit {
                    text: root.game_path;
                    edited(text) => {
                        root.game_path = text;
                    }
                }

                Button {
                    width: 200px;
                    text: "Open game location";
                    clicked => {
                        root.request_game_path();
                    }
                }
            }
        }

        VerticalLayout {
            spacing: 10px;
            VerticalLayout {
                HorizontalLayout {
                    alignment: center;
                    spacing: 25px;
                    Switch {
                        text: "Overwrite existing files";
                        checked: true;
                        toggled() => {
                            root.overwrite = !root.overwrite;
                        }
                    }

                    Switch {
                        text: "Extract directly (Faster - Less disk usage - Can't create backup)";
                        checked: false;
                        toggled() => {
                            root.overwrite = true;
                            root.direct = !root.direct;
                        }
                    }
                }

                Text {
                    horizontal-alignment: center;
                    text: "(Backups not yet implemented, but not supported when extracting directly to game directory)";
                }
            }

            Button {
                text: "Uncompress and move into game dir";
                clicked => {
                    root.mod();
                }
            }

            Text {
                text: root.footer;
                horizontal-alignment: center;
            }
        }
    }

    about_popup := PopupWindow {

        close-on-click: false;

        Rectangle {
            background: root.background;
            border-width: 1px;

            VerticalLayout {
                padding: 16px;
                VerticalLayout {
                    Text {
                        text: "Game modding tool";
                    }

                    Text {
                        text: "Version 0.1.0";
                    }

                    Text {
                        text: "Inverse Software";
                    }
                }

                StandardButton {
                    kind: ok;
                    clicked => {
                        about_popup.close();
                    }
                }
            }
        }
    }
}
